DROP TABLE MEMBER;

CREATE TABLE MEMBER (
	MEMBER_ID	VARCHAR2(500)	PRIMARY KEY,
	MEMBER_PW	VARCHAR2(500)	NOT NULL,
	MEMBER_NAME	VARCHAR2(500)	NOT NULL,
	MEMBER_NICNAME	VARCHAR2(1000)	NOT NULL,
	MEMBER_EMAIL	VARCHAR2(1000)	NOT NULL,
	MEMBER_PHONE	VARCHAR2(100)	NOT NULL,
	MEMBER_ADDR	VARCHAR2(2000)	NOT NULL,
	MEMBER_IP	VARCHAR2(100)	NOT NULL,
	MEMBER_GRADE	VARCHAR2(100)	NOT NULL,
	MEMBER_JOIN	VARCHAR2(2)	NOT NULL,
	MEMBER_NOTIFY	VARCHAR2(2)	NOT NULL,
	MEMBER_FACE	VARCHAR2(2)	NOT NULL,
	MEMBER_AUTO	VARCHAR2(2)	NOT NULL
);