DROP TABLE MEMBER;

CREATE TABLE MEMBER (
	MEMBER_ID	VARCHAR2(500)	PRIMARY KEY,
	MEMBER_PW	VARCHAR2(500)	NOT NULL,
	MEMBER_NAME	VARCHAR2(500)	NOT NULL,
	MEMBER_NICNAME	VARCHAR2(1000)	DEFAULT '일반회원' NOT NULL,
	MEMBER_EMAIL	VARCHAR2(1000)	NOT NULL,
	MEMBER_PHONE	VARCHAR2(100)	NOT NULL,
	MEMBER_ADDR	VARCHAR2(2000)	NOT NULL,
	MEMBER_IP	VARCHAR2(100)	NOT NULL,
	MEMBER_GRADE	VARCHAR2(100)	NOT NULL,
	MEMBER_JOIN	VARCHAR2(2)	NOT NULL,
	MEMBER_NOTIFY	VARCHAR2(2)	NOT NULL,
	MEMBER_FACE	VARCHAR2(2)	NOT NULL,
	MEMBER_AUTO	VARCHAR2(2)	NOT NULL,
	
	CONSTRAINT MEMBER_GRADE_CK CHECK (MEMBER_GRADE IN ('관리자','일반회원','강사회원')),
	CONSTRAINT MEMBER_JOIN_CK CHECK (MEMBER_JOIN IN ('Y','N')),
	CONSTRAINT MEMBER_NOTIFY_CK CHECK (MEMBER_NOTIFY IN ('Y','N')),
	CONSTRAINT MEMBER_FACE_CK CHECK (MEMBER_FACE IN ('Y','N')),
	CONSTRAINT MEMBER_AUTO_CK CHECK (MEMBER_AUTO IN ('Y','N'))
);

DROP TABLE CLASS;

CREATE TABLE CLASS (
	CLASS_NO	NUMBER	PRIMARY KEY,
	CLASS_TITLE	VARCHAR2(1000)	NULL,
	CLASS_DESC	VARCHAR2(4000)	NULL,
	CLASS_LOC	VARCHAR2(1000)	NULL,
	CLASS_CATEGORY	VARCHAR2(500)	NULL,
	CLASS_MEMBER_NUM	NUMBER	NULL,
	CLASS_PRICE	NUMBER	NULL,
	CLASS_SALE	NUMBER	DEFAULT 0 NULL,
	MEMBER_ID	VARCHAR2(500)	NOT NULL,
	
	CONSTRAINT CLASS_SALE_CK CHECK(CLASS_SALE BETWEEN 0 AND 100),
	CONSTRAINT CLASS_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
	
);

DROP TABLE PRODUCT;

CREATE TABLE  PRODUCT  (
	 PRODUCT_NO 	NUMBER	PRIMARY KEY,
	 PRODUCT_NAME 	VARCHAR2(500)	NULL,
	 PRODUCT_CATEGORY 	VARCHAR2(500)	NULL,
	 PRODUCT_PRICE 	NUMBER	NULL,
	 PRODUCT_DESC 	VARCHAR2(8000)	NULL,
	 PRODUCT_LOC 	VARCHAR2(1000)	NULL,
	 PRODUCT_DEL 	VARCHAR2(200)	NULL,
	 PRODUCT_SALE 	NUMBER	DEFAULT 0 NULL,
	 
	 CONSTRAINT PRODUCT_SALE_CK CHECK(PRODUCT_SALE BETWEEN 0 AND 100)
);

DROP TABLE BOARD;

CREATE TABLE  BOARD  (
	 BOARD_NO 	NUMBER	PRIMARY KEY,
	 BOARD_NOTICE_NO 	NUMBER	NULL,
	 BOARD_QNA_NO 	NUMBER	NULL,
	 BOARD_TITLE 	VARCHAR2(500)	NULL,
	 BOARD_CONTENT 	VARCHAR2(2000)	NULL,
	 BOARD_DATE 	DATE DEFAULT SYSDATE NULL,
	 BOARD_READCOUNT 	NUMBER DEFAULT 0	NULL,
	 BOARD_GROUPNO 	NUMBER	NULL,
	 BOARD_GROUPSEQ 	NUMBER	NULL,
	 BOARD_TITLETAB 	NUMBER	NULL,
	 BOARD_DELFLAG 	VARCHAR2(2)	NULL,
	 BOARD_CATEGORY 	VARCHAR2(2)	NULL,
	 BOARD_PW 	VARCHAR2(100)	NULL,
	 MEMBER_ID 	VARCHAR2(500)	NOT NULL,
	 
	 CONSTRAINT BOARD_DELFLAG_CK CHECK (BOARD_DELFLAG IN ('Y','N')),
	 CONSTRAINT BOARD_CATEGORY_CK CHECK (BOARD_CATEGORY IN ('Q','N')),
	 CONSTRAINT BOARD_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
	 
);

DROP TABLE FILE_TABLE;

CREATE TABLE  FILE_TABLE  (
	 FILE_NUM 	NUMBER	PRIMARY KEY,
	 FILE_PATH 	VARCHAR2(100)	NULL,
	 FILE_ORI_NAME 	VARCHAR2(30)	NULL,
	 FILE_NEW_NAME 	VARCHAR2(30)	NULL,
	 FILE_TYPE 	VARCHAR2(10)	NULL,
	 FILE_DATE 	DATE DEFAULT SYSDATE	NULL,
	 FILE_SIZE 	VARCHAR2(40)	NULL,
	 MEMBER_ID 	VARCHAR2(500)	NOT NULL,
	 PRODUCT_NO 	NUMBER	NOT NULL,
	 CLASS_NO 	NUMBER	NOT NULL,
	 REVIEW_NO 	NUMBER	NOT NULL,
	 EVENT_NO 	NUMBER	NOT NULL,
	 
	 CONSTRAINT FILE_TABLE_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
	 CONSTRAINT FILE_TABLE_PRODUCT_NO_FK FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT (PRODUCT_NO),
	 CONSTRAINT FILE_TABLE_CLASS_NO_FK FOREIGN KEY (CLASS_NO) REFERENCES CLASS (CLASS_NO),
	 CONSTRAINT FILE_TABLE_REVIEW_NO_FK FOREIGN KEY (REVIEW_NO) REFERENCES REVIEW (REVIEW_NO),
	 CONSTRAINT FILE_TABLE_EVENT_NO_FK FOREIGN KEY (EVENT_NO) REFERENCES EVENT (EVENT_NO)
	 
);

DROP TABLE PAYMENT;

CREATE TABLE  PAYMENT  (
	 PAYMENT_NO 	NUMBER	PRIMARY KEY,
	 PAYMENT_NUM 	NUMBER	NULL,
	 PAYMENT_PRICE 	NUMBER	NULL,
	 PAYMENT_DATE 	DATE DEFAULT SYSDATE	NULL,
	 MEMBER_ID 	VARCHAR2(500)	NOT NULL,
	 PRODUCT_NO 	NUMBER	NOT NULL,
	 BASKET_NO 	NUMBER	NOT NULL,
	 CLASS_NO 	NUMBER	NOT NULL,
	 PAYMENT_DEL 	VARCHAR2(50) DEFAULT '결제완료'	NULL,
	 
	 CONSTRAINT PAYMENT_DEL_CK CHECK (PAYMENT_DEL IN ('결제완료','배송준비중','배송중','배송완료')),
	 CONSTRAINT PAYMENT_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
	 CONSTRAINT PAYMENT_PRODUCT_NO_FK FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT (PRODUCT_NO),
	 CONSTRAINT PAYMENT_BASKET_NO_FK FOREIGN KEY (BASKET_NO) REFERENCES BASKET (BASKET_NO),
	 CONSTRAINT PAYMENT_CLASS_NO_FK FOREIGN KEY (CLASS_NO) REFERENCES CLASS (CLASS_NO)
	 
	 
);

DROP TABLE BASKET;

CREATE TABLE  BASKET  (
	 BASKET_NO 	NUMBER	PRIMARY KEY,
	 BASKET_NUM 	NUMBER	NULL,
	 BASKET_PRICE 	NUMBER	NULL,
	 PRODUCT_NO 	NUMBER	NOT NULL,
	 MEMBER_ID 	VARCHAR2(500)	NOT NULL,
	 
	 CONSTRAINT BASKET_PRODUCT_NO_FK FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT (PRODUCT_NO),
	 CONSTRAINT BASKET_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
	 
);

DROP TABLE EVENT;

CREATE TABLE  EVENT  (
	 EVENT_NO 	NUMBER	PRIMARY KEY,
	 EVENT_TITLE 	VARCHAR2(500)	NULL,
	 EVENT_DESC 	VARCHAR2(4000)	NULL,
	 EVENT_START 	DATE	NULL,
	 EVNET_END 	DATE	NULL,
	 EVENT_NOTI 	VARCHAR2(2)	NULL,
	 MEMBER_ID 	VARCHAR2(500)	NOT NULL,
	 CLASS_NO 	NUMBER	NOT NULL,
	 PRODUCT_NO 	NUMBER	NOT NULL,
	 
	 CONSTRAINT EVENT_NOTI_CK CHECK (EVENT_NOTI IN('Y','N'))
	 CONSTRAINT EVENT_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
	 CONSTRAINT EVENT_CLASS_NO_FK FOREIGN KEY (CLASS_NO) REFERENCES CLASS (CLASS_NO),
	 CONSTRAINT EVENT_PRODUCT_NO_FK FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT (PRODUCT_NO)
);

DROP TABLE REVIEW;

CREATE TABLE  REVIEW  (
	 REVIEW_NO 	NUMBER	PRIMARY KEY,
	 REVIEW_TITLE 	VARCHAR2(1000)	NULL,
	 REVIEW_RATE 	NUMBER	NULL,
	 REVIEW_DATE 	DATE DEFAULT SYSDATE	NULL,
	 REVIEW_CONTENT 	VARCHAR2(4000)	NULL,
	 PRODUCT_NO 	NUMBER	NOT NULL,
	 CLASS_NO 	NUMBER	NOT NULL,
	 MEMBER_ID 	VARCHAR2(500)	NOT NULL,
	 
	 CONSTRAINT REVIEW_PRODUCT_NO_FK FOREIGN KEY (PRODUCT_NO) REFERENCES PRODUCT (PRODUCT_NO),
	 CONSTRAINT REVIEW_CLASS_NO_FK FOREIGN KEY (CLASS_NO) REFERENCES CLASS (CLASS_NO),
	 CONSTRAINT REVIEW_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

DROP TABLE CHATTING;

CREATE TABLE  CHATTING (
	 CHATTING_NO 	NUMBER	PRIMARY KEY,
	 CHATTING_CONTENT 	VARCHAR2(8000)	NULL,
	 CHATTING_DATE 	DATE	NULL,
	 CHAT_NO 	NUMBER	NOT NULL,
	 
	 CONSTRAINT CHATTING_CHAT_NO_FK FOREIGN KEY (CHAT_NO) REFERENCES CHAT (CHAT_NO)
);

DROP TABLE CHAT;

CREATE TABLE  CHAT  (
	 CHAT_NO 	NUMBER	PRIMARY KEY,
	 MEMBER_ID 	VARCHAR2(500)	NOT NULL,
	 CONSULT_ID 	VARCHAR2(500)	NULL,
	 CHAT_CONTENT 	VARCHAR2(500)	NULL,
	 CHAT_DATE 	DATE	NULL,
	 CONSTRAINT CHAT_MEMBER_ID_FK FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

DROP TABLE DETAIL;

CREATE TABLE  DETAIL  (
	 DETAIL_NO 	NUMBER	NOT NULL PRIMARY KEY,
	 DETAIL_DATE 	DATE	NULL,
	 DETAIL_MEMBER_NUM 	NUMBER	NULL,
	 CLASS_NO 	NUMBER	NOT NULL,
	 CONSTRAINT DETAIL_CLASS_NO_FK FOREIGN KEY (CLASS_NO) REFERENCES CLASS (CLASS_NO),
);

ALTER TABLE  MEMBER  ADD CONSTRAINT  PK_MEMBER  PRIMARY KEY (
	 MEMBER_ID 
);

ALTER TABLE  CLASS  ADD CONSTRAINT  PK_CLASS  PRIMARY KEY (
	 CLASS_NO 
);

ALTER TABLE  PRODUCT  ADD CONSTRAINT  PK_PRODUCT  PRIMARY KEY (
	 PRODUCT_NO 
);

ALTER TABLE  BOARD  ADD CONSTRAINT  PK_BOARD  PRIMARY KEY (
	 BOARD_NO 
);

ALTER TABLE  FILE_TABLE  ADD CONSTRAINT  PK_FILE_TABLE  PRIMARY KEY (
	 FILE_NUM 
);

ALTER TABLE  PAYMENT  ADD CONSTRAINT  PK_PAYMENT  PRIMARY KEY (
	 PAYMENT_NO 
);

ALTER TABLE  BASKET  ADD CONSTRAINT  PK_BASKET  PRIMARY KEY (
	 BASKET_NO 
);

ALTER TABLE  EVENT  ADD CONSTRAINT  PK_EVENT  PRIMARY KEY (
	 EVENT_NO 
);

ALTER TABLE  REVIEW  ADD CONSTRAINT  PK_REVIEW  PRIMARY KEY (
	 REVIEW_NO 
);

ALTER TABLE  CHATTING  ADD CONSTRAINT  PK_CHATTING  PRIMARY KEY (
	 CHATTING_NO 
);

ALTER TABLE  CHAT  ADD CONSTRAINT  PK_CHAT  PRIMARY KEY (
	 CHAT_NO 
);

ALTER TABLE  DETAIL  ADD CONSTRAINT  PK_DETAIL  PRIMARY KEY (
	 DETAIL_NO 
);